server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: api
          uri: lb://client-app
          predicates:
            - Path=/api/healthCheck
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


