server:
  port: 0

spring:
  application:
    name: client-app

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}